version: "3"

services:
    backend:
        container_name: backend
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        image: adminseeker/multi-image-steganography-backend
        networks: 
            web:
        ports:
            - 5000:5000
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        image: adminseeker/multi-image-steganography-frontend
        networks: 
            web:
        ports: 
            - 8081:80
        links:
            - backend     

networks: 
    web: